name: nft_app_test
description: NFT App Test
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web3_connect: ^0.0.3
  http: ^0.13.5
  web_socket_channel: ^2.2.0
  provider: ^6.0.4
  flutter_ipfs: ^0.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  flutter_screenutil: ^5.6.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  wallet_connect: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - contracts/NftAppTest.json
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
